### ISSUE TITLE
add list upstream and downstream methods

### ISSUE THREAD

**Issue by sckott** [richfitz/toxiproxyr#4]
via https://github.com/Shopify/toxiproxy#http-api

did on my fork: https://github.com/sckott/toxiproxyr/commit/6a7cf9ba8fdc0be1edd6247258f64a45171ec457

**Comment by richfitz** [comment]
With the change to API version 2, this is probably no longer needed?  But let me know if there are other changes that would be useful (especially if you're using this in anything).  Heads up that I totally changed the API to reflect the API change in toxiproxy server
