### ISSUE TITLE
Examples of other services

### ISSUE THREAD

**Issue by sckott** [richfitz/toxiproxyr#5]
added an example of connecting to mysql in readme on my fork 

https://github.com/sckott/toxiproxyr#mysql-testing

happy to put it elsewhere if you want, a vignette?

**Comment by richfitz** [comment]
Nice one Scott!  A vignette would be lovely but you don't have to do that (though I'm not sure when I will get time to focus on this package as it's not a huge priority).

Do you want to send a PR or should I just pull the old-fashioned way?

Perhaps we should consider this package for ropensci (direct or via onboarding) given the number of API packages we use, too...

**Comment by sckott** [comment]
> A vignette would be lovely but you don't have to do that

so you don't want one? happy to start it. i could leave in readme, but i imagine you don't want a cluttered readme

PR is good

> consider this package for ropensci

Up to you, you're the maintainer

**Comment by richfitz** [comment]
I will copy over the content here into the vignette soon, if you're OK with that @sckott; would you like authorship credit?

**Comment by sckott** [comment]
okay, no that's okay
